# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c08824fd364bfeee857eddafdaed674f4f5e9897edc046011ab4fbfdc150453eaf5d566cb2b268d702636aad39f7d300a19f1c5aa7e6d94dd7a381297f122b66

test:
  secret_key_base: b5704ac10fa4244e6a3d41a026efeb12dbbade3359539ada0da5988ae0eb7015d5def2f638ec175518a74e1ba78086b5446e1b7fde9aa5850f156d213f52e3da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
